//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGA.skillsser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="skillsser.skillsserviceSoap")]
    public interface skillsserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegisterUser(string firstName, string lastName, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckValidCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckValidCustomer(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFirstName(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAboutYourOrganisation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SaveAboutYourOrganisation(int customerId, string company, string jobRole, string jobTitle, string sector, string industry, string pModel, string noofpeople);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssessmentForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AssessmentForm(int customerId, string answer1, string answer2, string answer3, string answer4, string answer5, string answer6, string answer7, string answer8, string answer9, string answer10);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface skillsserviceSoapChannel : SGA.skillsser.skillsserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class skillsserviceSoapClient : System.ServiceModel.ClientBase<SGA.skillsser.skillsserviceSoap>, SGA.skillsser.skillsserviceSoap {
        
        public skillsserviceSoapClient() {
        }
        
        public skillsserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public skillsserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public skillsserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public skillsserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegisterUser(string firstName, string lastName, string emailAddress) {
            return base.Channel.RegisterUser(firstName, lastName, emailAddress);
        }
        
        public int CheckValidCustomer(string customerId) {
            return base.Channel.CheckValidCustomer(customerId);
        }
        
        public string GetFirstName(string customerId) {
            return base.Channel.GetFirstName(customerId);
        }
        
        public int SaveAboutYourOrganisation(int customerId, string company, string jobRole, string jobTitle, string sector, string industry, string pModel, string noofpeople) {
            return base.Channel.SaveAboutYourOrganisation(customerId, company, jobRole, jobTitle, sector, industry, pModel, noofpeople);
        }
        
        public int AssessmentForm(int customerId, string answer1, string answer2, string answer3, string answer4, string answer5, string answer6, string answer7, string answer8, string answer9, string answer10) {
            return base.Channel.AssessmentForm(customerId, answer1, answer2, answer3, answer4, answer5, answer6, answer7, answer8, answer9, answer10);
        }
    }
}
